name: Habeeb Custom Action Demo
on:
  push:
    branches:
      - main

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v4
      # we checked out code because we were using path to action. The action file needed to be present on the runner to work
      - name: calling custom action yml
        id: greet
       # uses: ./ #the location of action (function). This says current dir
        uses: actions2026/greeting-action@v1.0
        with:
          username: Obalola
      - name: Using Action output
        run: echo "Action says - ${{ steps.greet.outputs.message }}"
